application: playground
module: default
version: 1
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: automatic  # default value
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 80

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /phaser.js
  static_files: phaser.js
  upload: phaser.js
- url: /app.js
  static_files: app.js
  upload: app.js
- url: /phaser2.png
  static_files: phaser2.png
  upload: phaser2.png
- url: /.*
  script: _go_app